import { Modal } from "@/components/Modal";
import Link from "next/link";
import { notFound } from "next/navigation";
import { eq, asc } from "drizzle-orm";
import { db, schema, sql } from "@/db";
import { requireStaff, scopeUnit } from "@/lib/auth";
import { Page, Card, Table, Td, Badge, Flash, Field, Input, Select, Textarea, Btn } from "@/components/ui";
import { fmtData, fmtDataHora, getSettings, hoje } from "@/lib/utils";
import { okrs, FONTES, CONFIANCA, OBJ_STATUS, SAUDE, PROJ_STATUS } from "@/lib/estrategia";
import { salvarObjetivo, salvarKR, excluirKR, checkinKR } from "../../actions";

export const dynamic = "force-dynamic";

export default async function Objetivo({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const s = await requireStaff(); const { id } = await params; const sp = await searchParams; const oid = Number(id); const cfg = await getSettings();
  const [o] = await db.select().from(schema.objectives).where(eq(schema.objectives.id, oid)); if (!o) notFound(); const u = scopeUnit(s); if (u !== null && o.unitId !== null && o.unitId !== u) notFound();
  const ok = await okrs(o.ciclo, u); const obj = ok.objetivos.find(x => x.id === oid); if (!obj) notFound();
  const [checkins, projetos, users, units] = await Promise.all([sql<{ id: number; keyResultId: number; data: string; valor: number | null; confianca: number | null; comentario: string | null; userNome: string | null }[]>`SELECT id, key_result_id AS "keyResultId", data::text, valor::float, confianca, comentario, user_nome AS "userNome" FROM kr_checkins WHERE key_result_id IN (SELECT id FROM key_results WHERE objective_id=${oid}) ORDER BY created_at DESC LIMIT 30`, sql<{ id: number; nome: string; status: string; saude: string; owner: string | null }[]>`SELECT p.id, p.nome, p.status, p.saude, u.nome AS owner FROM projects p LEFT JOIN users u ON u.id=p.owner_user_id WHERE p.objective_id=${oid} ORDER BY p.status`, sql<{ id: number; nome: string }[]>`SELECT id, nome FROM users WHERE ativo AND role <> 'LEITURA' ORDER BY nome`, db.select().from(schema.units).orderBy(asc(schema.units.nome))]);
  const pode = ["DIRECAO", "RH", "DIRETOR_UNIDADE"].includes(s.role); const gestao = ["DIRECAO", "RH", "DIRETOR_UNIDADE", "GESTOR", "FINANCEIRO", "OPERACOES", "COMERCIAL"].includes(s.role);
  return (
    <Page title={obj.titulo} sub={<span className="flex flex-wrap items-center gap-2"><Badge v={obj.status === "CONCLUIDO" ? "APROVADA" : obj.status === "CANCELADO" ? "CANCELADA" : "EM_ADMISSAO"} label={OBJ_STATUS[obj.status]} /> {obj.pilar ?? "—"} · {obj.owner ?? "sem dono"} · {obj.unidade ?? "rede"} · ciclo {o.ciclo} · progresso <b>{obj.progresso === null ? "—" : `${obj.progresso}%`}</b> · <Link className="text-acao" href="/estrategia/okrs">OKRs</Link></span>}>
      <Flash ok={sp.ok} erro={sp.erro} />
      {obj.descricao && <p className="mb-4 text-sm text-slate-700">{obj.descricao}</p>}
      <div className="grid gap-4 lg:grid-cols-[1fr_360px] lg:items-start">
        <div className="space-y-4">
          <Card title="Resultados-chave">
            <Table head={["Resultado-chave", "Inicial → Meta", "Atual", "Progresso", "Confiança", "Dono", "Prazo", ""]} empty="Nenhum KR. Adicione ao lado.">{obj.krs.map(k => <tr key={k.id}><Td><div className="font-medium">{k.titulo}</div>{k.fonte && <div className="text-xs text-acao">lido do sistema: {FONTES[k.fonte.slice(8)]?.nome ?? k.fonte}</div>}</Td><Td className="whitespace-nowrap text-xs tabular-nums">{k.valor_inicial} → {k.valor_meta} {k.metrica ?? ""} {k.direcao === "DESCER" ? "↓" : "↑"}</Td><Td className="tabular-nums font-medium">{k.valor_atual === null ? "—" : k.valor_atual}</Td><Td><div className="flex items-center gap-2"><div className="h-2 w-20 overflow-hidden rounded bg-mist"><div className={`h-2 ${k.progresso === null ? "" : k.progresso >= 70 ? "bg-ok" : k.progresso >= 40 ? "bg-aviso" : "bg-erro"}`} style={{ width: `${k.progresso ?? 0}%` }} /></div><span className="text-xs tabular-nums">{k.progresso === null ? "—" : `${k.progresso}%`}</span></div></Td><Td>{k.confianca ? <Badge v={k.confianca === 3 ? "APROVADA" : k.confianca === 2 ? "PENDENTE" : "REJEITADA"} label={CONFIANCA[k.confianca]} /> : <span className="text-xs text-slate-400">—</span>}</Td><Td className="text-xs">{k.owner ?? "—"}</Td><Td className="text-xs">{fmtData(k.prazo)}</Td>
              <Td><div className="flex gap-1">{(gestao || k.owner_user_id === s.id) && obj.status === "ATIVO" && <Modal label={"Check-in"} kind="ghost"><form action={checkinKR} className="space-y-2"><input type="hidden" name="id" value={k.id} /><input type="hidden" name="objectiveId" value={oid} /><Field label="Data"><Input name="data" type="date" defaultValue={hoje()} /></Field>{!k.fonte && <Field label={`Valor atual (${k.metrica ?? ""})`}><Input name="valor" type="number" step="0.01" defaultValue={k.valor_atual ?? ""} /></Field>}<Field label="Confiança de bater a meta"><Select name="confianca" defaultValue={k.confianca ?? 2}>{[1, 2, 3].map(n => <option key={n} value={n}>{n} · {CONFIANCA[n]}</option>)}</Select></Field><Field label="Comentário"><Textarea name="comentario" className="min-h-[50px]" /></Field><Btn small>Registrar</Btn></form></Modal>}{pode && <Modal label={"editar"} kind="link"><form action={salvarKR} className="space-y-2"><input type="hidden" name="id" value={k.id} /><input type="hidden" name="objectiveId" value={oid} /><Field label="Resultado-chave"><Input name="titulo" defaultValue={k.titulo} required /></Field><div className="grid grid-cols-3 gap-1"><Field label="Inicial"><Input name="valorInicial" type="number" step="0.01" defaultValue={k.valor_inicial} /></Field><Field label="Meta"><Input name="valorMeta" type="number" step="0.01" defaultValue={k.valor_meta} required /></Field><Field label="Unidade"><Input name="metrica" defaultValue={k.metrica ?? ""} /></Field></div><Field label="Direção"><Select name="direcao" defaultValue={k.direcao}><option value="SUBIR">Subir</option><option value="DESCER">Descer</option></Select></Field><Field label="Fonte automática"><Select name="fonte" defaultValue={k.fonte?.slice(8) ?? ""}><option value="">Manual (check-ins)</option>{Object.entries(FONTES).map(([f, v]) => <option key={f} value={f}>{v.nome}</option>)}</Select></Field><div className="grid grid-cols-2 gap-1"><Field label="Dono"><Select name="ownerUserId" defaultValue={k.owner_user_id ?? ""}><option value="">—</option>{users.map(x => <option key={x.id} value={x.id}>{x.nome}</option>)}</Select></Field><Field label="Prazo"><Input name="prazo" type="date" defaultValue={k.prazo ?? ""} /></Field></div><div className="flex gap-1"><Btn small>Salvar</Btn><Btn small kind="ghost" danger formAction={excluirKR}>Excluir</Btn></div></form></Modal>}</div></Td></tr>)}</Table>
          </Card>
          <Card title="Projetos ligados a este objetivo"><Table head={["Projeto", "Situação", "Saúde", "Dono"]} empty="Nenhum projeto ligado. Crie em Projetos e escolha este objetivo.">{projetos.map(p => <tr key={p.id}><Td><Link className="text-acao" href={`/estrategia/projetos/${p.id}`}>{p.nome}</Link></Td><Td className="text-xs">{PROJ_STATUS[p.status]}</Td><Td><Badge v={p.saude === "VERDE" ? "APROVADA" : p.saude === "AMARELO" ? "PENDENTE" : "REJEITADA"} label={SAUDE[p.saude]} /></Td><Td className="text-xs">{p.owner ?? "—"}</Td></tr>)}</Table></Card>
          <Card title="Check-ins recentes"><ul className="space-y-1 text-sm">{checkins.length === 0 && <li className="text-slate-500">Nenhum check-in ainda.</li>}{checkins.map(c => { const k = obj.krs.find(x => x.id === c.keyResultId); return <li key={c.id}><span className="text-xs text-slate-500">{fmtData(c.data)} · {c.userNome}</span> · <b>{k?.titulo ?? "KR"}</b>{c.valor !== null ? ` → ${c.valor}` : ""}{c.confianca ? ` · confiança ${CONFIANCA[c.confianca]}` : ""}{c.comentario ? ` — ${c.comentario}` : ""}</li>; })}</ul></Card>
        </div>
        {pode && <div className="space-y-4">
          <Card title="Novo resultado-chave"><form action={salvarKR} className="space-y-2"><input type="hidden" name="objectiveId" value={oid} /><Field label="Resultado-chave"><Input name="titulo" required placeholder="Ex.: Inadimplência abaixo de 4%" /></Field><div className="grid grid-cols-3 gap-2"><Field label="Inicial"><Input name="valorInicial" type="number" step="0.01" defaultValue={0} /></Field><Field label="Meta"><Input name="valorMeta" type="number" step="0.01" required /></Field><Field label="Unidade"><Input name="metrica" placeholder="%, alunos, R$" /></Field></div><Field label="Direção"><Select name="direcao" defaultValue="SUBIR"><option value="SUBIR">Subir até a meta</option><option value="DESCER">Descer até a meta</option></Select></Field><Field label="Fonte automática (opcional)" hint="Lido do sistema a cada abertura; sem fonte, o dono faz check-ins."><Select name="fonte" defaultValue=""><option value="">Manual</option>{Object.entries(FONTES).map(([f, v]) => <option key={f} value={f}>{v.nome}</option>)}</Select></Field><div className="grid grid-cols-2 gap-2"><Field label="Dono"><Select name="ownerUserId" defaultValue={s.id}>{users.map(x => <option key={x.id} value={x.id}>{x.nome}</option>)}</Select></Field><Field label="Prazo"><Input name="prazo" type="date" defaultValue={`${o.ciclo.slice(0, 4)}-12-15`} /></Field></div><Btn small>Adicionar KR</Btn></form></Card>
          <Card title="Editar objetivo"><form action={salvarObjetivo} className="space-y-2"><input type="hidden" name="id" value={oid} /><input type="hidden" name="ciclo" value={o.ciclo} /><Field label="Objetivo"><Input name="titulo" defaultValue={o.titulo} required /></Field><Field label="Por que importa"><Textarea name="descricao" className="min-h-[50px]" defaultValue={o.descricao ?? ""} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Pilar"><Select name="pilar" defaultValue={o.pilar ?? ""}>{cfg.estrategia.pilares.map(p => <option key={p}>{p}</option>)}</Select></Field><Field label="Situação"><Select name="status" defaultValue={o.status}>{Object.entries(OBJ_STATUS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select></Field></div><div className="grid grid-cols-2 gap-2"><Field label="Dono"><Select name="ownerUserId" defaultValue={o.ownerUserId ?? ""}>{users.map(x => <option key={x.id} value={x.id}>{x.nome}</option>)}</Select></Field><Field label="Abrangência"><Select name="unitId" defaultValue={o.unitId ?? ""}><option value="">Rede</option>{units.map(x => <option key={x.id} value={x.id}>{x.nome}</option>)}</Select></Field></div><Field label="Ordem"><Input name="ordem" type="number" defaultValue={o.ordem} /></Field><Btn small kind="ghost">Salvar</Btn></form></Card>
        </div>}
      </div>
      <p className="mt-3 text-xs text-slate-500">Última leitura das fontes automáticas: {fmtDataHora(new Date())}.</p>
    </Page>
  );
}
