import Link from "next/link";
import { redirect } from "next/navigation";
import { requireSession, scopeUnit, can } from "@/lib/auth";
import { db, schema, sql } from "@/db";
import { asc } from "drizzle-orm";
import { Page, Card, Table, Td, Badge, Flash, Field, Select, Btn, Input, Textarea } from "@/components/ui";
import { PrintButton } from "@/components/PrintButton";
import { fmtData, getSettings, hoje } from "@/lib/utils";
import { healthGeral, registrarSnapshot, tendencia } from "@/lib/command-center";
import { okrs, portfolio, SAUDE } from "@/lib/estrategia";
import { salvarPendencia, decidirPendencia } from "./actions";

export const dynamic = "force-dynamic";
const cor = (n: number) => n >= 80 ? "text-ok" : n >= 60 ? "text-aviso" : "text-erro";
const bg = (n: number) => n >= 80 ? "bg-emerald-50 border-emerald-200" : n >= 60 ? "bg-amber-50 border-amber-200" : "bg-red-50 border-red-200";

export default async function CommandCenter({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const s = await requireSession(); if (!["DIRECAO", "RH", "DIRETOR_UNIDADE", "FINANCEIRO"].includes(s.role)) redirect("/"); const sp = await searchParams; const cfg = await getSettings();
  const scope = scopeUnit(s); const unitId = scope ?? (sp.unidade ? Number(sp.unidade) : null);
  const hg = await healthGeral(unitId); await registrarSnapshot(unitId, hg.geral, Object.fromEntries(hg.dominios.map(d => [d.chave, d.score])));
  const [trend, units, pend, porUnidade] = await Promise.all([tendencia(unitId), scope ? Promise.resolve([]) : db.select().from(schema.units).orderBy(asc(schema.units.nome)),
    sql<{ id: number; titulo: string; area: string | null; descricao: string | null; prazo: string | null; status: string; responsavel: string | null; decision_id: number | null }[]>`SELECT p.id, p.titulo, p.area, p.descricao, p.prazo::text, p.status, u.nome AS responsavel, p.decision_id FROM exec_pending p LEFT JOIN users u ON u.id=p.responsavel_user_id ORDER BY (p.status='ABERTA') DESC, (p.status='ADIADA') DESC, p.prazo NULLS LAST, p.id`,
    scope || sp.unidade ? Promise.resolve([]) : (async () => {
      // por unidade: usa o retrato de hoje quando já existe (evita recalcular 4× a cada abertura); calcula e guarda quando falta
      const us = await db.select().from(schema.units).orderBy(asc(schema.units.nome));
      const snaps = await sql<{ unit_id: number; geral: number; scores: Record<string, number> }[]>`SELECT unit_id, geral, scores FROM health_snapshots WHERE data=${hoje()} AND unit_id IS NOT NULL`;
      return Promise.all(us.map(async u => { const sn = snaps.find(x => x.unit_id === u.id); if (sn) return { id: u.id, nome: u.nome, geral: sn.geral, scores: sn.scores }; const h = await healthGeral(u.id); const scores = Object.fromEntries(h.dominios.map(d => [d.chave, d.score])); await registrarSnapshot(u.id, h.geral, scores); return { id: u.id, nome: u.nome, geral: h.geral, scores }; }));
    })()]);
  const users = await sql<{ id: number; nome: string }[]>`SELECT id, nome FROM users WHERE ativo AND role IN ('DIRECAO','RH','FINANCEIRO','DIRETOR_UNIDADE') ORDER BY nome`;
  const [est, pf] = await Promise.all([okrs(cfg.estrategia.cicloAtual, unitId), portfolio(unitId)]);
  const abertas = pend.filter(p => p.status !== "DECIDIDA"); const semana = trend.length > 7 ? trend[trend.length - 8] : trend[0]; const delta = semana ? hg.geral - semana.geral : null;
  const podeDecidir = can.aprovar(s, cfg.alcadas.pops);
  return (
    <Page title="Command Center" sub={`Visão única da Direção · ${fmtData(hoje())} · Health Geral pondera Pessoas ${hg.pesos.pessoas}%, Processos ${hg.pesos.processos}%, Matrículas ${hg.pesos.matriculas}%, Atendimento ${hg.pesos.atendimento}%, Financeiro ${hg.pesos.financeiro}%`}
      actions={<>{!scope && <form className="flex items-end gap-2 print:hidden"><Field label="Unidade"><Select name="unidade" defaultValue={unitId ?? ""}><option value="">Rede</option>{units.map(u => <option key={u.id} value={u.id}>{u.nome}</option>)}</Select></Field><Btn kind="ghost">Ver</Btn></form>}<PrintButton /></>}>
      <Flash ok={sp.ok} erro={sp.erro} />
      <div className="mb-4 grid gap-3 lg:grid-cols-[220px_1fr]">
        <div className={`rounded-md border p-4 ${bg(hg.geral)}`}><div className="text-xs font-medium text-slate-600">Health Geral</div><div className={`text-5xl font-semibold ${cor(hg.geral)}`}>{hg.geral}</div><div className="text-xs text-slate-600">{delta === null ? "primeiro registro" : delta === 0 ? "estável na semana" : `${delta > 0 ? "+" : ""}${delta} na semana`} · {hg.alertas.filter(a => a.nivel === "ALTO").length} alerta(s) alto(s)</div></div>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{hg.dominios.map(d => <Link key={d.chave} href={d.href} className={`rounded-md border p-3 ${bg(d.score)}`}><div className="text-xs font-medium text-slate-600">{d.nome}</div><div className={`text-3xl font-semibold ${cor(d.score)}`}>{d.score}</div><div className="mt-1 space-y-0.5 text-[11px] text-slate-600">{d.kpis.map(k => <div key={k.label} className="flex justify-between gap-2"><span>{k.label}</span><span className="font-medium text-ink">{k.valor}</span></div>)}</div></Link>)}</div>
      </div>
      <div className="grid gap-4 lg:grid-cols-2 lg:items-start">
        <Card title={`Alertas consolidados (${hg.alertas.length})`}>{hg.alertas.length === 0 ? <p className="text-sm text-slate-600">Nenhum indicador fora da meta. Indicadores ainda sem dados não geram alerta.</p> : <ul className="space-y-1 text-sm">{hg.alertas.map((a, i) => <li key={i} className="flex gap-2"><Badge v={a.nivel === "ALTO" ? "REJEITADA" : "PENDENTE"} label={a.nivel === "ALTO" ? "alto" : "médio"} /><Link className="text-ink hover:text-acao" href={a.href}>{a.texto}</Link></li>)}</ul>}</Card>
        <Card title="Por que este Health Geral?"><div className="space-y-2 text-sm">{hg.dominios.map(d => <div key={d.chave}><div className="flex justify-between"><span className="font-medium">{d.nome}</span><span className={`tabular-nums ${cor(d.score)}`}>{d.score} × {hg.pesos[d.chave]}%</span></div>{d.fatores.length ? <ul className="ml-3 text-xs text-slate-600">{d.fatores.map((f, i) => <li key={i}>{f.peso} · {f.texto}</li>)}</ul> : <div className="ml-3 text-xs text-slate-400">sem descontos</div>}</div>)}</div></Card>
        {porUnidade.length > 0 && <Card title="Por unidade (retrato de hoje)"><Table head={["Unidade", "Geral", ...hg.dominios.map(d => d.nome.split(" ")[0])]}>{porUnidade.map(u => <tr key={u.id}><Td><Link className="text-acao" href={`/command-center?unidade=${u.id}`}>{u.nome}</Link></Td><Td className={`font-semibold ${cor(u.geral)}`}>{u.geral}</Td>{hg.dominios.map(d => <Td key={d.chave} className={`tabular-nums ${cor(u.scores[d.chave] ?? 0)}`}>{u.scores[d.chave] ?? "—"}</Td>)}</tr>)}</Table></Card>}
        <Card title={`Estratégia ${cfg.estrategia.cicloAtual}`} actions={<Btn small kind="ghost" href="/estrategia">Abrir</Btn>}><div className="mb-2 flex items-baseline gap-3"><span className={`text-3xl font-semibold ${est.progressoCiclo === null ? "text-slate-400" : cor(est.progressoCiclo)}`}>{est.progressoCiclo === null ? "—" : `${est.progressoCiclo}%`}</span><span className="text-xs text-slate-500">dos OKRs · {pf.ativos} projeto(s) ativo(s) · {pf.vermelhos} em risco · {pf.marcosAtrasados} marco(s) atrasado(s)</span></div><ul className="space-y-1 text-sm">{est.objetivos.filter(o => o.status === "ATIVO").map(o => <li key={o.id} className="flex justify-between gap-2"><Link className="text-ink hover:text-acao" href={`/estrategia/okrs/${o.id}`}>{o.titulo}</Link><span className={`tabular-nums ${o.progresso === null ? "text-slate-400" : cor(o.progresso)}`}>{o.progresso === null ? "—" : `${o.progresso}%`}</span></li>)}</ul>{pf.rows.filter(r => r.saude === "VERMELHO" && ["EM_ANDAMENTO", "PAUSADO", "PLANEJADO"].includes(r.status)).slice(0, 3).map(r => <div key={r.id} className="mt-1 text-xs"><Badge v="REJEITADA" label={SAUDE[r.saude]} /> <Link className="text-acao" href={`/estrategia/projetos/${r.id}`}>{r.nome}</Link></div>)}</Card>
        <Card title="Tendência (retratos diários)">{trend.length < 2 ? <p className="text-sm text-slate-600">O retrato é guardado a cada abertura desta tela; a tendência aparece a partir do segundo dia.</p> : <div className="flex items-end gap-1" style={{ height: 120 }}>{trend.slice(-30).map(t => <div key={t.data} title={`${fmtData(t.data)}: ${t.geral}`} className={`flex-1 rounded-t ${t.geral >= 80 ? "bg-ok" : t.geral >= 60 ? "bg-aviso" : "bg-erro"}`} style={{ height: `${t.geral}%` }} />)}</div>}{trend.length >= 2 && <div className="mt-1 flex justify-between text-[10px] text-slate-500"><span>{fmtData(trend.slice(-30)[0].data)}</span><span>{fmtData(trend[trend.length - 1].data)}</span></div>}</Card>
      </div>
      <Card title={`Decisões pendentes da Direção (${abertas.length})`} className="mt-4"><div id="decisoes" />
        <Table head={["Decisão", "Área", "Prazo", "Responsável", "Situação", ""]} empty="Nenhuma decisão pendente.">{pend.map(p => <tr key={p.id} className={p.status === "DECIDIDA" ? "opacity-60" : ""}><Td><div className="font-medium">{p.titulo}</div>{p.descricao && <div className="text-xs text-slate-600">{p.descricao}</div>}{p.decision_id && <div className="text-xs"><Link className="text-acao" href="/governanca/decisoes?status=VIGENTE">decisão #{p.decision_id} no Decision Log</Link></div>}</Td><Td className="text-xs">{p.area ?? "—"}</Td><Td className={`text-xs ${p.prazo && p.prazo < hoje() && p.status !== "DECIDIDA" ? "font-medium text-erro" : ""}`}>{fmtData(p.prazo)}</Td><Td className="text-xs">{p.responsavel ?? "—"}</Td><Td><Badge v={p.status === "DECIDIDA" ? "APROVADA" : p.status === "ADIADA" ? "PENDENTE" : "EM_ADMISSAO"} label={p.status === "DECIDIDA" ? "Decidida" : p.status === "ADIADA" ? "Adiada" : "Aberta"} /></Td>
          <Td>{podeDecidir && p.status !== "DECIDIDA" && <details className="relative print:hidden"><summary className="cursor-pointer rounded-md bg-acao px-2.5 py-1 text-xs font-medium text-white">Decidir</summary><form action={decidirPendencia} className="mt-1 w-80 max-w-[85vw] space-y-2 rounded-md border border-line bg-white p-3 text-xs shadow-lg"><input type="hidden" name="id" value={p.id} /><Field label="Decisão tomada (vai para o Decision Log)"><Textarea name="decisao" className="min-h-[60px]" /></Field><Field label="Revisar em"><Input name="revisarEm" type="date" /></Field><div className="flex gap-1"><Btn small name="status" value="DECIDIDA">Registrar decisão</Btn><Btn small kind="ghost" name="status" value="ADIADA">Adiar</Btn></div><Field label="Novo prazo (se adiar)"><Input name="prazo" type="date" /></Field></form></details>}</Td></tr>)}</Table>
        {can.editar(s) && <form action={salvarPendencia} className="mt-3 grid gap-2 border-t border-line pt-3 print:hidden sm:grid-cols-[1fr_180px_140px_180px_auto]"><Field label="Nova decisão pendente"><Input name="titulo" required /></Field><Field label="Área"><Select name="area" defaultValue={cfg.governanca.areas[cfg.governanca.areas.length - 1]}>{cfg.governanca.areas.map(a => <option key={a}>{a}</option>)}</Select></Field><Field label="Prazo"><Input name="prazo" type="date" /></Field><Field label="Responsável"><Select name="responsavelUserId" defaultValue={s.id}>{users.map(u => <option key={u.id} value={u.id}>{u.nome}</option>)}</Select></Field><div className="flex items-end"><Btn small kind="ghost">Adicionar</Btn></div></form>}
      </Card>
      <p className="mt-3 text-xs text-slate-500 print:hidden">Cada bloco leva ao módulo. Pesos e metas em Configurações → Command Center (chave commandCenter).</p>
    </Page>
  );
}
