import Link from "next/link";
import { notFound } from "next/navigation";
import { eq, asc, desc } from "drizzle-orm";
import { db, schema, sql } from "@/db";
import { requireStaff, scopeUnit } from "@/lib/auth";
import { Page, Card, Table, Td, Badge, Flash, Field, Input, Select, Textarea, Btn, Stat } from "@/components/ui";
import { fmtData, getSettings, hoje } from "@/lib/utils";
import { PROJ_STATUS, SAUDE, RISCO_STATUS } from "@/lib/estrategia";
import { brl } from "@/lib/operacoes";
import { salvarProjeto, salvarMarco, concluirMarco, statusReport, salvarRisco } from "../../actions";

export const dynamic = "force-dynamic";

export default async function Projeto({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const s = await requireStaff(); const { id } = await params; const sp = await searchParams; const pid = Number(id); const cfg = await getSettings(); const h = hoje();
  const [p] = await db.select().from(schema.projects).where(eq(schema.projects.id, pid)); if (!p) notFound(); const u = scopeUnit(s); if (u !== null && p.unitId !== null && p.unitId !== u) notFound();
  const [marcos, updates, riscos, users, units, objetivos] = await Promise.all([db.select().from(schema.milestones).where(eq(schema.milestones.projectId, pid)).orderBy(asc(schema.milestones.prazo)), db.select().from(schema.projectUpdates).where(eq(schema.projectUpdates.projectId, pid)).orderBy(desc(schema.projectUpdates.data), desc(schema.projectUpdates.id)).limit(12), db.select().from(schema.projectRisks).where(eq(schema.projectRisks.projectId, pid)).orderBy(desc(schema.projectRisks.probabilidade), desc(schema.projectRisks.impacto)), sql<{ id: number; nome: string }[]>`SELECT id, nome FROM users WHERE ativo AND role <> 'LEITURA' ORDER BY nome`, db.select().from(schema.units).orderBy(asc(schema.units.nome)), sql<{ id: number; titulo: string }[]>`SELECT id, titulo FROM objectives WHERE status='ATIVO' ORDER BY ordem`]);
  const gestao = ["DIRECAO", "RH", "DIRETOR_UNIDADE", "GESTOR", "FINANCEIRO", "OPERACOES", "COMERCIAL"].includes(s.role); const dono = p.ownerUserId === s.id; const owner = users.find(x => x.id === p.ownerUserId)?.nome; const objetivo = objetivos.find(o => o.id === p.objectiveId)?.titulo;
  const ok = marcos.filter(m => m.concluidoEm).length; const atrasados = marcos.filter(m => !m.concluidoEm && m.prazo < h).length; const ativo = ["PLANEJADO", "EM_ANDAMENTO", "PAUSADO"].includes(p.status);
  return (
    <Page title={p.nome} sub={<span className="flex flex-wrap items-center gap-2"><Badge v={p.saude === "VERDE" ? "APROVADA" : p.saude === "AMARELO" ? "PENDENTE" : "REJEITADA"} label={SAUDE[p.saude]} /><Badge v={p.status === "CONCLUIDO" ? "APROVADA" : p.status === "CANCELADO" ? "CANCELADA" : "EM_ADMISSAO"} label={PROJ_STATUS[p.status]} />{owner ?? "sem dono"} · {units.find(x => x.id === p.unitId)?.nome ?? "rede"}{objetivo ? <> · serve a <Link className="text-acao" href={`/estrategia/okrs/${p.objectiveId}`}>{objetivo}</Link></> : ""} · <Link className="text-acao" href="/estrategia/projetos">projetos</Link></span>}>
      <Flash ok={sp.ok} erro={sp.erro} />
      <div className="mb-4 grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Marcos" value={marcos.length ? `${ok}/${marcos.length}` : "—"} hint={atrasados ? `${atrasados} atrasado(s)` : undefined} /><Stat label="Prazo" value={fmtData(p.fim) || "—"} hint={p.inicio ? `início ${fmtData(p.inicio)}` : undefined} /><Stat label="Orçamento" value={<span className="text-xl">{p.orcamento ? `${brl(p.gasto ?? 0)} / ${brl(p.orcamento)}` : "—"}</span>} hint={p.orcamento && p.gasto && Number(p.gasto) > Number(p.orcamento) ? "estourado" : undefined} /><Stat label="Riscos abertos altos" value={riscos.filter(r => r.status === "ABERTO" && r.probabilidade * r.impacto >= 6).length} /></div>
      {(p.resultadoEsperado || p.descricao) && <Card className="mb-4"><dl className="grid gap-3 text-sm sm:grid-cols-2">{p.resultadoEsperado && <div><dt className="text-xs font-medium text-slate-500">Resultado esperado</dt><dd>{p.resultadoEsperado}</dd></div>}{p.descricao && <div><dt className="text-xs font-medium text-slate-500">Descrição</dt><dd className="whitespace-pre-wrap">{p.descricao}</dd></div>}</dl></Card>}
      <div className="grid gap-4 lg:grid-cols-[1fr_360px] lg:items-start">
        <div className="space-y-4">
          <Card title="Marcos"><div id="marcos" /><Table head={["", "Marco", "Prazo", "Responsável", "Concluído em"]} empty="Nenhum marco. Quebre o projeto em 3 a 8 entregas com data.">{marcos.map(m => <tr key={m.id} className={!m.concluidoEm && m.prazo < h ? "bg-red-50/40" : ""}><Td>{gestao && ativo ? <form action={concluirMarco}><input type="hidden" name="id" value={m.id} /><input type="hidden" name="projectId" value={pid} /><button aria-label="marco" className={`flex h-5 w-5 items-center justify-center rounded border text-xs ${m.concluidoEm ? "border-ok bg-ok text-white" : "border-slate-400 bg-white"}`}>{m.concluidoEm ? "✓" : ""}</button></form> : <span className={`inline-block h-3 w-3 rounded-full ${m.concluidoEm ? "bg-ok" : "bg-slate-300"}`} />}</Td><Td className={m.concluidoEm ? "text-slate-500 line-through" : ""}>{m.titulo}</Td><Td className={`text-xs ${!m.concluidoEm && m.prazo < h ? "font-medium text-erro" : ""}`}>{fmtData(m.prazo)}</Td><Td className="text-xs">{users.find(x => x.id === m.responsavelUserId)?.nome ?? "—"}</Td><Td className="text-xs">{fmtData(m.concluidoEm)}</Td></tr>)}</Table>
            {gestao && ativo && <form action={salvarMarco} className="mt-3 grid gap-2 border-t border-line pt-3 sm:grid-cols-[1fr_140px_180px_auto]"><input type="hidden" name="projectId" value={pid} /><Field label="Novo marco"><Input name="titulo" required /></Field><Field label="Prazo"><Input name="prazo" type="date" required /></Field><Field label="Responsável"><Select name="responsavelUserId" defaultValue={p.ownerUserId ?? ""}><option value="">—</option>{users.map(x => <option key={x.id} value={x.id}>{x.nome}</option>)}</Select></Field><div className="flex items-end"><Btn small kind="ghost">Adicionar</Btn></div></form>}</Card>
          <Card title="Status reports">{updates.length === 0 ? <p className="text-sm text-slate-500">Nenhum status report. A cada {cfg.estrategia.atualizacaoProjetoDias} dias o dono registra: feito, próximo, riscos e saúde.</p> : <ul className="space-y-3 text-sm">{updates.map(up => <li key={up.id} className="rounded-md border border-line p-3"><div className="mb-1 flex items-center gap-2 text-xs text-slate-500"><Badge v={up.saude === "VERDE" ? "APROVADA" : up.saude === "AMARELO" ? "PENDENTE" : "REJEITADA"} label={SAUDE[up.saude]} />{fmtData(up.data)} · {up.userNome}</div>{up.feito && <div><span className="text-xs font-medium text-slate-500">Feito · </span>{up.feito}</div>}{up.proximo && <div><span className="text-xs font-medium text-slate-500">Próximo · </span>{up.proximo}</div>}{up.riscos && <div><span className="text-xs font-medium text-slate-500">Riscos · </span>{up.riscos}</div>}</li>)}</ul>}</Card>
          <Card title="Riscos"><div id="riscos" /><Table head={["Risco", "Prob.", "Impacto", "Nível", "Mitigação", "Situação", ""]} empty="Nenhum risco registrado.">{riscos.map(r => { const n = r.probabilidade * r.impacto; return <tr key={r.id}><Td>{r.descricao}</Td><Td>{r.probabilidade}</Td><Td>{r.impacto}</Td><Td><Badge v={n >= 6 ? "REJEITADA" : n >= 3 ? "PENDENTE" : "ATIVO"} label={n >= 6 ? "alto" : n >= 3 ? "médio" : "baixo"} /></Td><Td className="text-xs">{r.mitigacao ?? "—"}</Td><Td className="text-xs">{RISCO_STATUS[r.status]}</Td><Td>{gestao && <details className="relative"><summary className="cursor-pointer text-xs text-acao">editar</summary><form action={salvarRisco} className="mt-1 w-72 max-w-[85vw] space-y-2 rounded-md border border-line bg-white p-3 text-xs shadow-lg"><input type="hidden" name="id" value={r.id} /><input type="hidden" name="projectId" value={pid} /><Field label="Risco"><Input name="descricao" defaultValue={r.descricao} /></Field><div className="grid grid-cols-2 gap-1"><Field label="Probabilidade"><Select name="probabilidade" defaultValue={r.probabilidade}>{[1, 2, 3].map(n2 => <option key={n2} value={n2}>{n2}</option>)}</Select></Field><Field label="Impacto"><Select name="impacto" defaultValue={r.impacto}>{[1, 2, 3].map(n2 => <option key={n2} value={n2}>{n2}</option>)}</Select></Field></div><Field label="Mitigação"><Input name="mitigacao" defaultValue={r.mitigacao ?? ""} /></Field><Field label="Situação"><Select name="status" defaultValue={r.status}>{Object.entries(RISCO_STATUS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select></Field><Btn small>Salvar</Btn></form></details>}</Td></tr>; })}</Table>
            {gestao && ativo && <form action={salvarRisco} className="mt-3 grid gap-2 border-t border-line pt-3 sm:grid-cols-[1fr_90px_90px_1fr_auto]"><input type="hidden" name="projectId" value={pid} /><Field label="Novo risco"><Input name="descricao" required /></Field><Field label="Prob. (1–3)"><Select name="probabilidade" defaultValue="2">{[1, 2, 3].map(n => <option key={n} value={n}>{n}</option>)}</Select></Field><Field label="Impacto (1–3)"><Select name="impacto" defaultValue="2">{[1, 2, 3].map(n => <option key={n} value={n}>{n}</option>)}</Select></Field><Field label="Mitigação"><Input name="mitigacao" /></Field><div className="flex items-end"><Btn small kind="ghost">Adicionar</Btn></div></form>}</Card>
        </div>
        <div className="space-y-4">
          {(gestao || dono) && ativo && <Card title="Status report"><form action={statusReport} className="space-y-2"><input type="hidden" name="projectId" value={pid} /><div className="grid grid-cols-2 gap-2"><Field label="Data"><Input name="data" type="date" defaultValue={h} /></Field><Field label="Saúde"><Select name="saude" defaultValue={p.saude}>{Object.entries(SAUDE).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select></Field></div><Field label="Feito desde o último"><Textarea name="feito" className="min-h-[50px]" /></Field><Field label="Próximos passos"><Textarea name="proximo" className="min-h-[50px]" /></Field><Field label="Riscos e pedidos de ajuda"><Textarea name="riscos" className="min-h-[40px]" /></Field><div className="grid grid-cols-2 gap-2"><Field label="Gasto até agora (R$)"><Input name="gasto" type="number" step="0.01" defaultValue={p.gasto ?? ""} /></Field><Field label="Situação"><Select name="status" defaultValue={p.status}>{Object.entries(PROJ_STATUS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select></Field></div><Btn small>Registrar</Btn></form></Card>}
          {gestao && <Card title="Editar projeto"><form action={salvarProjeto} className="space-y-2"><input type="hidden" name="id" value={pid} /><Field label="Nome"><Input name="nome" defaultValue={p.nome} required /></Field><Field label="Objetivo"><Select name="objectiveId" defaultValue={p.objectiveId ?? ""}><option value="">—</option>{objetivos.map(o => <option key={o.id} value={o.id}>{o.titulo}</option>)}</Select></Field><Field label="Resultado esperado"><Textarea name="resultadoEsperado" className="min-h-[40px]" defaultValue={p.resultadoEsperado ?? ""} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Dono"><Select name="ownerUserId" defaultValue={p.ownerUserId ?? ""}>{users.map(x => <option key={x.id} value={x.id}>{x.nome}</option>)}</Select></Field><Field label="Unidade"><Select name="unitId" defaultValue={p.unitId ?? ""}><option value="">Rede</option>{units.map(x => <option key={x.id} value={x.id}>{x.nome}</option>)}</Select></Field></div><div className="grid grid-cols-3 gap-2"><Field label="Situação"><Select name="status" defaultValue={p.status}>{Object.entries(PROJ_STATUS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Prioridade"><Select name="prioridade" defaultValue={p.prioridade}><option value="NORMAL">Normal</option><option value="ALTA">Alta</option><option value="BAIXA">Baixa</option></Select></Field><Field label="Orçamento"><Input name="orcamento" type="number" step="0.01" defaultValue={p.orcamento ?? ""} /></Field></div><div className="grid grid-cols-2 gap-2"><Field label="Início"><Input name="inicio" type="date" defaultValue={p.inicio ?? ""} /></Field><Field label="Fim"><Input name="fim" type="date" defaultValue={p.fim ?? ""} /></Field></div><Field label="Descrição"><Textarea name="descricao" className="min-h-[40px]" defaultValue={p.descricao ?? ""} /></Field><Btn small kind="ghost">Salvar</Btn></form></Card>}
        </div>
      </div>
    </Page>
  );
}
