import { Modal } from "@/components/Modal";
import Link from "next/link";
import { requireFinanceiro, scopeUnit } from "@/lib/auth";
import { db, schema, sql } from "@/db";
import { asc } from "drizzle-orm";
import { Page, Card, Table, Td, Badge, Flash, Field, Select, Btn, Stat, Input, Textarea } from "@/components/ui";
import { fmtData, fmtDataHora, getSettings, hoje } from "@/lib/utils";
import { inadimplencia, brl, ETAPA_COB, RESULTADO_COB, ACORDO_STATUS, REC_TIPO } from "@/lib/financeiro";
import { registrarCobranca, criarAcordo, baixarParcela, quebrarAcordo } from "../actions";

export const dynamic = "force-dynamic";

export default async function Inadimplencia({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const s = await requireFinanceiro(); const sp = await searchParams; const cfg = await getSettings(); const scope = scopeUnit(s); const unitId = scope ?? (sp.unidade ? Number(sp.unidade) : null); const so = sp.so ?? ""; const q = (sp.q ?? "").trim();
  const inad = await inadimplencia(unitId); const units = scope ? [] : await db.select().from(schema.units).orderBy(asc(schema.units.nome));
  let itens = so === "PENDENTES" ? inad.itens.filter(i => i.acaoPendente) : so === "NEGOCIAR" ? inad.itens.filter(i => i.dias >= 20) : inad.itens; if (q) itens = itens.filter(i => i.aluno_nome.toLowerCase().includes(q.toLowerCase()) || (i.responsavel ?? "").toLowerCase().includes(q.toLowerCase()));
  const acordos = await sql<{ id: number; aluno_nome: string; unidade: string; valor_original: number; valor_acordado: number; parcelas: number; status: string; created_at: Date; pagas: number; proxima: string | null; parcelas_json: { id: number; numero: number; vencimento: string; valor: number; pago_em: string | null }[] }[]>`SELECT a.id, a.aluno_nome, u.nome AS unidade, a.valor_original::float, a.valor_acordado::float, a.parcelas, a.status, a.created_at, (SELECT count(*) FROM agreement_installments p WHERE p.agreement_id=a.id AND p.pago_em IS NOT NULL)::int AS pagas, (SELECT min(p.vencimento)::text FROM agreement_installments p WHERE p.agreement_id=a.id AND p.pago_em IS NULL) AS proxima, coalesce((SELECT json_agg(json_build_object('id', p.id, 'numero', p.numero, 'vencimento', p.vencimento, 'valor', p.valor, 'pago_em', p.pago_em) ORDER BY p.numero) FROM agreement_installments p WHERE p.agreement_id=a.id), '[]'::json) AS parcelas_json FROM agreements a JOIN units u ON u.id=a.unit_id WHERE 1=1 ${unitId === null ? sql`` : sql`AND a.unit_id=${unitId}`} ORDER BY (a.status='ATIVO') DESC, a.created_at DESC LIMIT 100`;
  const h = hoje(); const podeCobrar = ["DIRECAO", "FINANCEIRO", "DIRETOR_UNIDADE", "RH"].includes(s.role);
  const familias = Object.values(itens.reduce<Record<string, typeof itens>>((a, i) => { (a[i.aluno_nome] = a[i.aluno_nome] ?? []).push(i); return a; }, {}));
  return (
    <Page title="Inadimplência e cobrança" sub={`Régua: ${(cfg.financeiro.regua as [number, string, string][]).map(r => `${r[0]}d ${ETAPA_COB[r[1]]}`).join(" → ")}. Cada título mostra em que etapa deveria estar e a última ação registrada.`} actions={<><Btn kind="ghost" href="/api/export/inadimplencia">Exportar CSV</Btn><Btn kind="ghost" href="/financeiro">Painel</Btn></>}>
      <Flash ok={sp.ok} erro={sp.erro} />
      <div className="mb-4 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5"><Stat label="Em aberto vencido" value={brl(inad.total)} hint={`${inad.itens.length} título(s) · ${inad.familias} família(s)`} /><Stat label="Inadimplência 90 dias" value={inad.taxa90 === null ? "—" : `${inad.taxa90}%`} />{inad.aging.slice(0, 3).map(a => <Stat key={a.faixa} label={a.faixa} value={brl(a.valor)} hint={`${a.n} título(s)`} />)}</div>
      <form className="mb-3 flex flex-wrap items-end gap-2 rounded-md border border-line bg-white p-3">{!scope && <Field label="Unidade"><Select name="unidade" defaultValue={unitId ?? ""}><option value="">Todas</option>{units.map(u => <option key={u.id} value={u.id}>{u.nome}</option>)}</Select></Field>}<Field label="Mostrar"><Select name="so" defaultValue={so}><option value="">Todos vencidos</option><option value="PENDENTES">Com ação da régua pendente</option><option value="NEGOCIAR">+20 dias (negociação)</option></Select></Field><Field label="Buscar"><Input name="q" defaultValue={q} placeholder="Aluno ou responsável" /></Field><Btn kind="ghost">Filtrar</Btn></form>
      <div className="space-y-3">{familias.length === 0 && <Card><p className="text-sm text-slate-500">Nenhum título vencido neste filtro.</p></Card>}
        {familias.map(f => { const total = f.reduce((a, i) => a + i.valor, 0); const pior = f.reduce((a, i) => Math.max(a, i.dias), 0); return (
          <Card key={f[0].aluno_nome} title={<span>{f[0].student_id ? <Link className="text-acao" href={`/matriculas/alunos/${f[0].student_id}#atendimento`}>{f[0].aluno_nome}</Link> : f[0].aluno_nome} <span className="ml-2 font-normal text-slate-500">{f[0].unidade} · {f[0].responsavel ?? ""} {f[0].telefone ?? ""}</span></span>} actions={<span className="text-sm font-medium text-erro">{brl(total)} · até {pior} dias</span>}>
            <Table head={["Título", "Competência", "Vencimento", "Dias", "Valor", "Etapa pela régua", "Última ação", ""]}>{f.map(i => <tr key={i.id} className={i.acaoPendente ? "bg-amber-50/40" : ""}><Td className="text-xs">{REC_TIPO[i.tipo]}</Td><Td className="text-xs">{i.competencia ?? "—"}</Td><Td>{fmtData(i.vencimento)}</Td><Td className={`tabular-nums ${i.dias > 90 ? "font-medium text-erro" : ""}`}>{i.dias}</Td><Td className="tabular-nums">{brl(i.valor)}</Td><Td>{i.etapa ? <Badge v={i.acaoPendente ? "PENDENTE" : "ATIVO"} label={`${ETAPA_COB[i.etapa]}${i.acaoPendente ? " · pendente" : ""}`} /> : <span className="text-xs text-slate-400">—</span>}</Td><Td className="text-xs">{i.ultima_etapa ? `${ETAPA_COB[i.ultima_etapa]} · ${RESULTADO_COB[i.ultimo_resultado ?? ""] ?? ""} · ${fmtDataHora(i.ultima_acao)}` : "nenhuma"}</Td>
              <Td>{podeCobrar && <Modal label={"Registrar contato"} kind="ghost"><form action={registrarCobranca} className="space-y-2"><input type="hidden" name="receivableId" value={i.id} /><input type="hidden" name="voltar" value="/financeiro/inadimplencia" /><Field label="Etapa"><Select name="etapa" defaultValue={i.etapa ?? "CONTATO"}>{Object.entries(ETAPA_COB).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Canal"><Input name="canal" defaultValue={i.canal ?? ""} /></Field><Field label="Resultado"><Select name="resultado" defaultValue="SEM_RETORNO">{Object.entries(RESULTADO_COB).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select></Field><Field label="Registro"><Textarea name="texto" className="min-h-[50px]" /></Field><Btn small>Salvar</Btn></form></Modal>}</Td></tr>)}</Table>
            {podeCobrar && f.length > 0 && <details className="mt-2"><summary className="cursor-pointer text-xs text-acao">Fechar acordo com estes títulos</summary><form action={criarAcordo} className="mt-2 grid gap-2 sm:grid-cols-4">{f.map(i => <input key={i.id} type="hidden" name="receivableId" value={i.id} />)}<Field label={`Valor acordado (original ${brl(total)})`}><Input name="valorAcordado" type="number" step="0.01" defaultValue={total.toFixed(2)} /></Field><Field label="Parcelas"><Input name="parcelas" type="number" min={1} defaultValue={1} /></Field><Field label="1ª parcela"><Input name="primeiraParcela" type="date" defaultValue={h} /></Field><div className="flex items-end"><Btn small>Criar acordo</Btn></div><p className="text-xs text-slate-500 sm:col-span-4">Desconto acima da sua alçada ({(cfg.financeiro.alcadaDescontoPct as Record<string, number>)[s.role] ?? 0}%) é bloqueado — peça à Direção.</p></form></details>}
          </Card>); })}
      </div>
      <Card title="Acordos" className="mt-4"><div id="acordos" />
        <Table head={["#", "Família", "Unidade", "Original", "Acordado", "Parcelas", "Situação", "Próxima", ""]} empty="Nenhum acordo.">{acordos.map(a => <tr key={a.id}><Td className="text-slate-500">{a.id}</Td><Td>{a.aluno_nome}</Td><Td>{a.unidade}</Td><Td className="tabular-nums">{brl(a.valor_original)}</Td><Td className="tabular-nums">{brl(a.valor_acordado)}</Td><Td>{a.pagas}/{a.parcelas}</Td><Td><Badge v={a.status === "CUMPRIDO" ? "APROVADA" : a.status === "ATIVO" ? "EM_ADMISSAO" : "REJEITADA"} label={ACORDO_STATUS[a.status]} /></Td><Td className={`text-xs ${a.proxima && a.proxima < h && a.status === "ATIVO" ? "font-medium text-erro" : ""}`}>{fmtData(a.proxima)}</Td>
          <Td>{a.status === "ATIVO" && podeCobrar && <Modal label={"parcelas"} kind="link"><div className="space-y-1">{a.parcelas_json.map(p => <div key={p.id} className="flex items-center justify-between gap-2"><span>{p.numero}ª · {fmtData(p.vencimento)} · {brl(p.valor)}</span>{p.pago_em ? <span className="text-ok">paga {fmtData(p.pago_em)}</span> : <form action={baixarParcela} className="flex items-center gap-1"><input type="hidden" name="id" value={p.id} /><Btn small kind="ghost">baixar</Btn></form>}</div>)}<form action={quebrarAcordo} className="pt-2"><input type="hidden" name="id" value={a.id} /><Btn small danger>Marcar como quebrado</Btn></form></div></Modal>}</Td></tr>)}</Table>
      </Card>
    </Page>
  );
}
